version: '3.9'

services:
  cloudtech:
    image: postgres:15.3
    container_name: cloudtech-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cloudtechDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
