import type { StyleDictionary, TDocumentDefinitions } from 'pdfmake/interfaces';
import { kardexListHeaderSection } from '../sections/headers';
import { footerSection, watermarkSection } from '../sections';

const tecnmLogoPath = 'src/pdf-documents/assets/tecnmLogo.png';

const styles: StyleDictionary = {
	header: {
		fontSize: 8,
		font: 'Roboto',
		alignment: 'center',
		color: 'white',
		bold: true,
	},
	bodyTableLeft: {
		fontSize: 7,
		font: 'Roboto',
		alignment: 'left',
		color: 'black',
		bold: true,
	},
	bodyTableRight: {
		fontSize: 7,
		font: 'Roboto',
		alignment: 'right',
		color: 'black',
		bold: true,
	},
};

export const getKardexListReport = (): TDocumentDefinitions => {
	const docDefinition: TDocumentDefinitions = {
		styles: styles,

		pageMargins: [20, 170, 20, 160],
		header: kardexListHeaderSection(),

		background: watermarkSection({
			image: tecnmLogoPath,
			alignment: 'center',
			opacity: 0.2,
			width: 400,
			margin: [0, 120, 0, 0],
		}),

		content: [
			{
				stack: [
					{
						layout: 'kardexListTableLayout',
						table: {
							headerRows: 2,
							widths: [
								'auto',
								'auto',
								'*',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
							],
							body: [
								// Header Rows
								[
									{
										text: 'MATERIAS CURSADAS',
										margin: [5, 0, 0, 0],
										fontSize: 8,
										font: 'Roboto',
										colSpan: 11,
										border: [false, false, false, false],
									},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
								],
								[
									{
										text: 'NO.',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'CLAVE',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'NOMBRE',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'CR',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'CAL',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'TC',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'PRIMERA',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'REPITE',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'ESPECIAL',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'EXAMEN',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'AC',
										style: 'header',
										border: [false, false, false, false],
									},
								],
								// Body table subjects taken
								[
									{ text: `01`, style: 'bodyTableLeft' },
									{ text: `ACF0901`, style: 'bodyTableLeft' },
									{ text: `CALCULO DIFERENCIAL`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `91`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `02`, style: 'bodyTableLeft' },
									{ text: `ACC0906`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE INVESTIGACION`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `94`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `03`, style: 'bodyTableLeft' },
									{ text: `AED1285`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE PROGRAMACION`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `78`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `04`, style: 'bodyTableLeft' },
									{ text: `AEF1041`, style: 'bodyTableLeft' },
									{ text: `MATEMATICAS DISCRETAS`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `91`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `05`, style: 'bodyTableLeft' },
									{ text: `SCH1024`, style: 'bodyTableLeft' },
									{ text: `TALLER DE ADMINISTRACION`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `78`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `06`, style: 'bodyTableLeft' },
									{ text: `ACA0907`, style: 'bodyTableLeft' },
									{ text: `TALLER DE ETICA`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `86`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `01`, style: 'bodyTableLeft' },
									{ text: `ACF0901`, style: 'bodyTableLeft' },
									{ text: `CALCULO DIFERENCIAL`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `91`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `02`, style: 'bodyTableLeft' },
									{ text: `ACC0906`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE INVESTIGACION`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `94`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `03`, style: 'bodyTableLeft' },
									{ text: `AED1285`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE PROGRAMACION`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `78`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `04`, style: 'bodyTableLeft' },
									{ text: `AEF1041`, style: 'bodyTableLeft' },
									{ text: `MATEMATICAS DISCRETAS`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `91`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `05`, style: 'bodyTableLeft' },
									{ text: `SCH1024`, style: 'bodyTableLeft' },
									{ text: `TALLER DE ADMINISTRACION`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `78`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `06`, style: 'bodyTableLeft' },
									{ text: `ACA0907`, style: 'bodyTableLeft' },
									{ text: `TALLER DE ETICA`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `86`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 2203 AGODIC2020`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `07`, style: 'bodyTableLeft' },
									{ text: `ACF0903`, style: 'bodyTableLeft' },
									{ text: `ALGEBRA LINEAL`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `2 2211 ENEJUN2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `08`, style: 'bodyTableLeft' },
									{ text: `ACF0902`, style: 'bodyTableLeft' },
									{
										text: `CALCULO INTEGRAL`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `2 2211 ENEJUN2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `09`, style: 'bodyTableLeft' },
									{ text: `AEC1008`, style: 'bodyTableLeft' },
									{
										text: `CONTABILIDAD FINANCIERA`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `85`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `2 2211 ENEJUN2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `10`, style: 'bodyTableLeft' },
									{ text: `AEF1052`, style: 'bodyTableLeft' },
									{
										text: `PROBABILIDAD Y ESTADISTICA`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `94`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `2 2211 ENEJUN2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `11`, style: 'bodyTableLeft' },
									{ text: `AED1286`, style: 'bodyTableLeft' },
									{
										text: `PROGRAMACION ORIENTADA A OBJETOS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `78`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `2 2211 ENEJUN2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `12`, style: 'bodyTableLeft' },
									{ text: `AEC1058`, style: 'bodyTableLeft' },
									{ text: `QUIMICA`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `99`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `2 2211 ENEJUN2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `13`, style: 'bodyTableLeft' },
									{ text: `ACF0904`, style: 'bodyTableLeft' },
									{ text: `CALCULO VECTORIAL`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 3 2213 AGODIC2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `14`, style: 'bodyTableLeft' },
									{ text: `SCC1005`, style: 'bodyTableLeft' },
									{
										text: `CULTURA EMPRESARIAL`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 3 2213 AGODIC2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `15`, style: 'bodyTableLeft' },
									{ text: `ACD0908`, style: 'bodyTableLeft' },
									{
										text: `DESARROLLO SUSTENTABLE`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 3 2213 AGODIC2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `16`, style: 'bodyTableLeft' },
									{ text: `AED1026`, style: 'bodyTableLeft' },
									{ text: `ESTRUCTURA DE DATOS`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `90`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 3 2213 AGODIC2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `17`, style: 'bodyTableLeft' },
									{ text: `SCF1006`, style: 'bodyTableLeft' },
									{ text: `FISICA GENERAL`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `97`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 3 2213 AGODIC2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `18`, style: 'bodyTableLeft' },
									{ text: `SCC1013`, style: 'bodyTableLeft' },
									{
										text: `INVESTIGACION DE OPERACIONES`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `1 3 2213 AGODIC2021`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `19`, style: 'bodyTableLeft' },
									{ text: `ACF0905`, style: 'bodyTableLeft' },
									{ text: `ECUACIONES DIFERENCIALES`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `85`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `4 2221 ENEJUN2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `20`, style: 'bodyTableLeft' },
									{ text: `AEF1031`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE BASES DE DATOS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `95`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `4 2221 ENEJUN2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `21`, style: 'bodyTableLeft' },
									{ text: `SCC1017`, style: 'bodyTableLeft' },
									{
										text: `METODOS NUMERICOS`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `4 2221 ENEJUN2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `22`, style: 'bodyTableLeft' },
									{ text: `SCD1018`, style: 'bodyTableLeft' },
									{
										text: `PRINCIPIOS ELECTRICOS Y APLICACIONES DIGITALES`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `4 2221 ENEJUN2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `23`, style: 'bodyTableLeft' },
									{ text: `SCD1022`, style: 'bodyTableLeft' },
									{ text: `SIMULACION`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `4 2221 ENEJUN2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `24`, style: 'bodyTableLeft' },
									{ text: `SCD1027`, style: 'bodyTableLeft' },
									{
										text: `TOPICOS AVANZADOS DE PROGRAMACION`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `93`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `4 2221 ENEJUN2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `25`, style: 'bodyTableLeft' },
									{ text: `SCD1003`, style: 'bodyTableLeft' },
									{
										text: `ARQUITECTURA DE COMPUTADORAS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `5 2223 AGODIC2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `26`, style: 'bodyTableLeft' },
									{ text: `SCC1007`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE INGENIERIA DE SOFTWARE`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `95`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `5 2223 AGODIC2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `27`, style: 'bodyTableLeft' },
									{ text: `AEC1034`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE TELECOMUNICACIONES`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `5 2223 AGODIC2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `28`, style: 'bodyTableLeft' },
									{ text: `SCC1010`, style: 'bodyTableLeft' },
									{ text: `GRAFICACION`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `95`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `5 2223 AGODIC2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `29`, style: 'bodyTableLeft' },
									{ text: `AEC1061`, style: 'bodyTableLeft' },
									{ text: `SISTEMAS OPERATIVOS`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `89`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `5 2223 AGODIC2022`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `30`, style: 'bodyTableLeft' },
									{ text: `SCD1011`, style: 'bodyTableLeft' },
									{ text: `INGENIERIA DE SOFTWARE`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `91`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `31`, style: 'bodyTableLeft' },
									{ text: `SCD1015`, style: 'bodyTableLeft' },
									{ text: `LENGUAJES Y AUTOMATAS I`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `100`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `32`, style: 'bodyTableLeft' },
									{ text: `SCC1014`, style: 'bodyTableLeft' },
									{
										text: `LENGUAJES DE INTERFAZ`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `98`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `33`, style: 'bodyTableLeft' },
									{ text: `SCD1021`, style: 'bodyTableLeft' },
									{
										text: `REDES DE COMPUTADORAS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `34`, style: 'bodyTableLeft' },
									{ text: `SCC1023`, style: 'bodyTableLeft' },
									{ text: `SISTEMAS PROGRAMABLES`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `76`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `35`, style: 'bodyTableLeft' },
									{ text: `SCA1025`, style: 'bodyTableLeft' },
									{ text: `TALLER DE BASES DE DATOS`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `90`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `36`, style: 'bodyTableLeft' },
									{ text: `SCA1026`, style: 'bodyTableLeft' },
									{
										text: `TALLER DE SISTEMAS OPERATIVOS`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `99`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `6 2231 ENEJUN2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `37`, style: 'bodyTableLeft' },
									{ text: `ISE9`, style: 'bodyTableLeft' },
									{
										text: `ACTIVIDADES COMPLEMENTARIAS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `EXC`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `7 2233 AGODIC2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `38`, style: 'bodyTableLeft' },
									{ text: `SCD1004`, style: 'bodyTableLeft' },
									{
										text: `CONMUTACION Y ENRUTAMIENTO DE REDES DE DATOS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `82`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `7 2233 AGODIC2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `39`, style: 'bodyTableLeft' },
									{ text: `CEG2201`, style: 'bodyTableLeft' },
									{
										text: `FUNDAMENTOS DE COMPUTO EN LA NUBE`,
										style: 'bodyTableLeft',
									},
									{ text: `6`, style: 'bodyTableRight' },
									{ text: `99`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `7 2233 AGODIC2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `40`, style: 'bodyTableLeft' },
									{ text: `SCG1009`, style: 'bodyTableLeft' },
									{
										text: `GESTION DE PROYECTOS DE SOFTWARE`,
										style: 'bodyTableLeft',
									},
									{ text: `6`, style: 'bodyTableRight' },
									{ text: `88`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `7 2233 AGODIC2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `41`, style: 'bodyTableLeft' },
									{ text: `SCD1016`, style: 'bodyTableLeft' },
									{ text: `LENGUAJES Y AUTOMATAS II`, style: 'bodyTableLeft' },
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `7 2233 AGODIC2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `42`, style: 'bodyTableLeft' },
									{ text: `ACA0909`, style: 'bodyTableLeft' },
									{ text: `TALLER DE INVESTIGACION I`, style: 'bodyTableLeft' },
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `98`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `7 2233 AGODIC2023`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `43`, style: 'bodyTableLeft' },
									{ text: `SCB1001`, style: 'bodyTableLeft' },
									{
										text: `ADMINISTRACION DE BASES DE DATOS`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `85`, style: 'bodyTableRight' },
									{ text: `2`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `44`, style: 'bodyTableLeft' },
									{ text: `CEG2202`, style: 'bodyTableLeft' },
									{
										text: `ARQUITECTURA DE SOLUCIONES EN LA NUBE`,
										style: 'bodyTableLeft',
									},
									{ text: `6`, style: 'bodyTableRight' },
									{ text: `99`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `45`, style: 'bodyTableLeft' },
									{ text: `SCA1002`, style: 'bodyTableLeft' },
									{
										text: `ADMINISTRACION DE REDES`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `99`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `46`, style: 'bodyTableLeft' },
									{ text: `SCC1012`, style: 'bodyTableLeft' },
									{
										text: `INTELIGENCIA ARTIFICIAL`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `99`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `47`, style: 'bodyTableLeft' },
									{ text: `AEB1055`, style: 'bodyTableLeft' },
									{
										text: `PROGRAMACION WEB`,
										style: 'bodyTableLeft',
									},
									{ text: `5`, style: 'bodyTableRight' },
									{ text: `98`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `48`, style: 'bodyTableLeft' },
									{ text: `SCC1019`, style: 'bodyTableLeft' },
									{
										text: `PROGRAMACION LOGICA Y FUNCIONAL`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `97`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `49`, style: 'bodyTableLeft' },
									{ text: `ACA0910`, style: 'bodyTableLeft' },
									{
										text: `TALLER DE INVESTIGACION II`,
										style: 'bodyTableLeft',
									},
									{ text: `4`, style: 'bodyTableRight' },
									{ text: `96`, style: 'bodyTableRight' },
									{ text: `1`, style: 'bodyTableRight' },
									{ text: `8 2241 ENEJUN2024`, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{
										text: ``,
										style: 'bodyTableLeft',
									},
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
							],
						},
					},
					// TODO: Here can be a tables of subjects being taken

					// Body table subjects to be studied
					{
						layout: 'kardexListTableLayout',
						table: {
							widths: [
								'auto',
								'auto',
								'*',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
								'auto',
							],
							body: [
								// Header Rows
								[
									{
										text: 'MATERIAS POR CURSAR',
										margin: [5, 0, 0, 0],
										fontSize: 8,
										font: 'Roboto',
										colSpan: 11,
										border: [false, false, false, false],
									},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
									{},
								],
								[
									{
										text: 'NO.',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'CLAVE',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'NOMBRE',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'CR',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'CAL',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'TC',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'PRIMERA',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'REPITE',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'ESPECIAL',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'EXAMEN',
										style: 'header',
										border: [false, false, false, false],
									},
									{
										text: 'AC',
										style: 'header',
										border: [false, false, false, false],
									},
								],
								// body table
								[
									{ text: `01`, style: 'bodyTableLeft' },
									{ text: `CEM2204`, style: 'bodyTableLeft' },
									{
										text: `ADMINISTRACIÓN DE CÓMPUTO EN LA NUBE`,
										style: 'bodyTableLeft',
									},
									{ text: `6`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: `0`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `02`, style: 'bodyTableLeft' },
									{ text: `CEg2203`, style: 'bodyTableLeft' },
									{
										text: `HERRAMIENTAS DE SOFTWARE EN LA NUBE`,
										style: 'bodyTableLeft',
									},
									{ text: `7`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: `0`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `03`, style: 'bodyTableLeft' },
									{ text: `ISC9`, style: 'bodyTableLeft' },
									{
										text: `RESIDENCIA PROFESIONAL`,
										style: 'bodyTableLeft',
									},
									{ text: `10`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: `0`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: `04`, style: 'bodyTableLeft' },
									{ text: `ISD9`, style: 'bodyTableLeft' },
									{
										text: `SERVICIO SOCIAL`,
										style: 'bodyTableLeft',
									},
									{ text: `10`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: `0`, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
								[
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{
										text: ``,
										style: 'bodyTableLeft',
									},
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableLeft' },
									{ text: ``, style: 'bodyTableRight' },
									{ text: ``, style: 'bodyTableRight' },
								],
							],
						},
					},
				],
			},
		],

		footer: (currentPage, pageCount) =>
			footerSection(currentPage, pageCount, {
				showSchoolarServiceFooter: true,
			}),
	};

	return docDefinition;
};
